version: "2.0"
services:
    bot:
        build: .
        network_mode: host
        depends_on:
            - redis
        restart: on-failure
    redis:
        image: redis:latest
        logging:
            driver: none
        restart: on-failure